package br.com.gustavo.nossotempo;

import android.app.*; import android.content.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable;
import android.os.*; import android.provider.Settings; import android.view.*; import android.widget.*;

public class FloatingCounterService extends Service {
    private final Handler h=new Handler(Looper.getMainLooper());private WindowManager wm;private View bubble;private TextView counter;private WindowManager.LayoutParams p;
    private final Runnable ticker=new Runnable(){public void run(){if(counter!=null){RelationshipTime.Parts t=RelationshipTime.now();counter.setText(t.mainLine()+"\n"+t.clockLine());}h.postDelayed(this,1000-System.currentTimeMillis()%1000);}};
    @Override public void onCreate(){super.onCreate();NotificationManager nm=getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel("counter","Contador em execução",NotificationManager.IMPORTANCE_LOW));PendingIntent pi=PendingIntent.getActivity(this,1,new Intent(this,MainActivity.class),PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Notification n=new Notification.Builder(this,"counter").setSmallIcon(R.drawable.app_icon).setContentTitle("Nosso Tempo está ativo").setContentText("Toque para configurar ou parar.").setContentIntent(pi).setOngoing(true).build();startForeground(7,n);if(Settings.canDrawOverlays(this))show();else stopSelf();}
    private void show(){wm=getSystemService(WindowManager.class);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setGravity(Gravity.CENTER);card.setPadding(dp(18),dp(12),dp(18),dp(12));GradientDrawable bg=new GradientDrawable();bg.setColors(new int[]{Color.rgb(66,20,52),Color.rgb(31,11,30)});bg.setCornerRadius(dp(22));bg.setStroke(dp(1),Color.rgb(255,112,157));card.setBackground(bg);TextView title=new TextView(this);title.setText("♥  NOSSO TEMPO");title.setTextColor(Color.rgb(255,176,201));title.setTextSize(13);title.setGravity(Gravity.CENTER);title.setTypeface(null,1);counter=new TextView(this);counter.setTextColor(Color.WHITE);counter.setTextSize(14);counter.setGravity(Gravity.CENTER);counter.setTypeface(null,1);counter.setPadding(0,dp(4),0,0);card.addView(title);card.addView(counter);bubble=card;
        p=new WindowManager.LayoutParams(dp(265),-2,WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY,WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE|WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,PixelFormat.TRANSLUCENT);p.gravity=Gravity.TOP|Gravity.START;p.x=dp(45);p.y=dp(120);
        card.setOnTouchListener(new View.OnTouchListener(){int sx,sy;float dx,dy;public boolean onTouch(View v,android.view.MotionEvent e){if(e.getAction()==0){sx=p.x;sy=p.y;dx=e.getRawX();dy=e.getRawY();return true;}if(e.getAction()==2){p.x=sx+(int)(e.getRawX()-dx);p.y=sy+(int)(e.getRawY()-dy);wm.updateViewLayout(bubble,p);return true;}return e.getAction()==1;}});wm.addView(card,p);ticker.run();}
    private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}@Override public void onDestroy(){h.removeCallbacks(ticker);if(bubble!=null&&wm!=null)wm.removeView(bubble);super.onDestroy();}@Override public android.os.IBinder onBind(Intent i){return null;}
}
